### ISSUE TITLE
Curve is not updating when connected to nested component

### ISSUE THREAD

**Issue by sklinov** [Error-256/react-bezier#2]
Please check out this sandbox
https://codesandbox.io/s/antd-graddable-cards-with-connections-nodes-and-cards-jx9o4?file=/src/App.tsx

The group ot top works fine and curve is updated when cards are dragged, but the ones on the bottom are not - keeps the shape of initial render. The behavior changes when it connects to nested component.
Not sure if it's an issue with `react-bezier` or maybe it has to do with `react-draggable` library.

Anyways, good job on creating that lib!

**Comment by Error-256** [comment]
Thank you for reporting the issue. It has been fixed at the moment.
